# Generated by Django 3.0.5 on 2021-06-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('contact_number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('email_field', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('tenth_cgpa', models.FloatField()),
                ('twelth_perc', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
                ('stipend', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
