# Generated by Django 3.0.5 on 2021-06-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_info_chomu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='chomu',
        ),
    ]
