# Generated by Django 3.0.5 on 2021-06-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_remove_info_chomu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='info',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='info',
            name='board',
        ),
        migrations.RemoveField(
            model_name='info',
            name='college',
        ),
        migrations.RemoveField(
            model_name='info',
            name='course',
        ),
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='info',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='info',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='info',
            name='school',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stipend',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='info',
            name='tenth_cgpa',
        ),
        migrations.RemoveField(
            model_name='info',
            name='twelth_perc',
        ),
    ]
