# Generated by Django 3.0.5 on 2021-06-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0004_auto_20210607_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
