# Generated by Django 2.2.24 on 2021-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('persons', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.CharField(choices=[('Andhadhun', 'Andhadhun'), ('Dhamaal', 'Dhamaal'), ('Kal hona ho', 'Kal hona ho'), ('3 idiots', '3 idiots'), ('Extraction', 'Extraction'), ('Bajrangi bhaijan', 'Bajrangi bhaijan'), ('Singham', 'Singham'), ('Delhi-6 ', 'Delhi-6 '), ('Dabbang', 'Dabbang'), ('The Shawshank Redemption', 'The Shawshank Redemption'), ('New york ', 'New york '), ('Special 26 ', 'Special 26 '), ('Hera pheri ', 'Hera pheri '), ('Citizen kane', 'Citizen kane'), ('10 things I hate about you', '10 things I hate about you'), ('Dark knight ', 'Dark knight '), ('Suicide squad', 'Suicide squad'), ('Matru ki bijli ka mandola', 'Matru ki bijli ka mandola'), ('Demon Slayer-Mugen train', 'Demon Slayer-Mugen train'), ('Welcome', 'Welcome')], max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
