# Generated by Django 2.2.24 on 2021-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
