# Generated by Django 2.2.24 on 2021-06-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livai', '0002_fruits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fruits',
        ),
    ]
